// examples/vue-app-example.vue
<!--
Example: Vue 3 with Composition API

This example demonstrates how to integrate Vercel Web Analytics
in a Vue 3 application.

Note: Route support is automatically enabled if you're using vue-router.
-->

<script setup lang="ts">
import { Analytics } from '@vercel/analytics/vue';
</script>

<template>
  <div id="app">
    <header>
      <h1>My Vue App</h1>
    </header>
    <main>
      <!-- Your app content here -->
    </main>
    <Analytics />
  </div>
</template>

<style scoped>
/* Your styles here */
</style>

// examples/react-app-example.tsx
/**
 * Example: Create React App
 * 
 * This example demonstrates how to integrate Vercel Web Analytics
 * in a React application (Create React App or similar).
 * 
 * Note: There is no route support with the plain React implementation.
 */

import { Analytics } from "@vercel/analytics/react";

export default function App() {
  return (
    <div className="app">
      <header>
        <h1>My React App</h1>
      </header>
      <main>
        {/* Your app content here */}
      </main>
      <Analytics />
    </div>
  );
}
